server:
  port: 8888

logging:
  file:
    name: mylog.log
    path: logs

spring:
  application:
    name: mytest
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root

mybatis:
  type-aliases-package: com.mybatis.model
  mapper-locations:
    - mapper/*
