server:
  port: 8888

logging:
  file:
    name: mylog.log
    path: logs

spring:
  application:
    name: mytest
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.101:3306/Test_mybatis
      username: root
      password: qwer1234

mybatis:
  type-aliases-package: com.mybatis.model
  mapper-locations:
    - mapper/*
